language: node_js
node_js:
- '0.11'
- '0.10'

before_script:
  - npm install -g gulp
script: gulp compile

deploy:
  provider: releases
  api_key: "39d4cc6bd426fd05e24bf39069508bd5aeadcba6"
  file:
     - ""
  skip_cleanup: true
  on:
    tags: true
